FROM openjdk:17-jdk-slim

# Install netcat for wait-for-it.sh
RUN apt-get update && apt-get install -y netcat

WORKDIR /app

COPY target/distqueue-application-1.0-SNAPSHOT.jar /app/consumer-application.jar
COPY wait-for-it.sh /app/wait-for-it.sh

ENV ROLE=consumer
ENV CONTROLLER_HOST=controller
ENV CONTROLLER_PORT=8090
ENV JAVA_OPTS=""

ENTRYPOINT ["/app/wait-for-it.sh", "controller", "8090", "sh", "-c", "java $JAVA_OPTS -jar /app/consumer-application.jar"]
