# Dockerfile.producer

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/distqueue-application-1.0-SNAPSHOT.jar /app/producer-application.jar

ENV ROLE=producer
ENV CONTROLLER_HOST=controller
ENV CONTROLLER_PORT=8090
ENV JAVA_OPTS=""

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/producer-application.jar"]
