services:
  broker1:
    image: broker-image
    container_name: broker1
    ports:
      - "8081:8080"  # Maps host port 8081 to container port 8080
    environment:
      - BROKER_ID=1  # Unique ID for each broker
      - BROKER_PORT=8080  # Internal port for the broker

  broker2:
    image: broker-image
    container_name: broker2
    ports:
      - "8082:8080"  # Maps host port 8082 to container port 8080
    environment:
      - BROKER_ID=2
      - BROKER_PORT=8080

  broker3:
    image: broker-image
    container_name: broker3
    ports:
      - "8083:8080"  # Maps host port 8083 to container port 8080
    environment:
      - BROKER_ID=3
      - BROKER_PORT=8080
