services:
  controller:
    image: distqueue/controller
    container_name: controller
    ports:
      - "8090:8090"
    environment:
      - ROLE=controller
      - PORT=8090
    networks:
      - distqueue-net

  broker1:
    image: distqueue/broker
    container_name: broker1
    environment:
      - ROLE=broker
      - BROKER_ID=1
      - HOST=broker1
      - PORT=8081
      - CONTROLLER_HOST=controller
      - CONTROLLER_PORT=8090
    ports:
      - "8085:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://broker1:8081/health"]
      interval: 5s
      timeout: 2s
      retries: 5
    depends_on:
      - controller
    networks:
      - distqueue-net

  broker2:
    image: distqueue/broker
    container_name: broker2
    environment:
      - ROLE=broker
      - BROKER_ID=2
      - HOST=broker2
      - PORT=8081
      - CONTROLLER_HOST=controller
      - CONTROLLER_PORT=8090
    ports:
      - "8086:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://broker1:8081/health"]
      interval: 5s
      timeout: 2s
      retries: 5
    depends_on:
      - controller
    networks:
      - distqueue-net

  broker3:
    image: distqueue/broker
    container_name: broker3
    environment:
      - ROLE=broker
      - BROKER_ID=3
      - HOST=broker3
      - PORT=8081
      - CONTROLLER_HOST=controller
      - CONTROLLER_PORT=8090
    ports:
      - "8087:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://broker1:8081/health"]
      interval: 5s
      timeout: 2s
      retries: 5
    depends_on:
      - controller
    networks:
      - distqueue-net

  producer:
    image: distqueue/producer
    container_name: producer
    environment:
      - ROLE=producer
      - CONTROLLER_HOST=controller
      - CONTROLLER_PORT=8090
    depends_on:
      - controller
    networks:
      - distqueue-net

  consumer:
    image: distqueue/consumer
    container_name: consumer
    environment:
      - ROLE=consumer
      - CONTROLLER_HOST=controller
      - CONTROLLER_PORT=8090
    depends_on:
      - controller
    networks:
      - distqueue-net

networks:
  distqueue-net:
    driver: bridge
